---
clone:
  git:
    image: quay.io/packet/drone-git
    tags: true

pipeline:
  build_image_ubuntu_test_env_image:
    image: docker
    commands:
      - docker build -t image-ubuntu-test-env --build-arg packet_api_token="$PACKET_API_TOKEN" --build-arg packer_deploy_key="$PACKER_DEPLOY_KEY" tools/packet-packer/ci
      - mkdir build
      - touch build/image-ubuntu-test-env
      - ln -s ../7 build/7
      - ln -s ../testing build/testing
      - ln -s ../tools build/tools
    secrets:
      - packet_api_token
      - packet_project
      - packer_deploy_key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  packer_validate_templates:
    group: ci1
    image: image-ubuntu-test-env
    commands:
      - ./tools/packet-packer/scripts/template-validate 7/templates 

  packer_centos7_t1small:
    group: ci1
    image: image-ubuntu-test-env
    commands:
      - mkdir -p build/packer_centos7_t1small
      - cd build/packer_centos7_t1small
      - ln -s ../../scripts scripts; ln -s ../../tools tools; ln -s ../../tools/packet-packer packet-packer
      - packer build -var 'plan=t1.small.x86' -var 'fac=sjc1' -var 'os=centos_7' -var 'mode=install' ../7/templates/centos-7.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  packer_centos7_c1small:
    group: ci1
    image: image-ubuntu-test-env
    commands:
      - mkdir -p build/packer_centos7_c1small
      - cd build/packer_centos7_c1small
      - ln -s ../../scripts scripts; ln -s ../../tools tools; ln -s ../../tools/packet-packer packet-packer
      - packer build -var 'plan=c1.small.x86' -var 'fac=sjc1' -var 'os=centos_7' -var 'mode=install' ../7/templates/centos-7.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  packer_centos7_x1small:
    group: ci1
    image: image-ubuntu-test-env
    commands:
      - mkdir -p build/packer_centos7_x1small
      - cd build/packer_centos7_x1small
      - ln -s ../../scripts scripts; ln -s ../../tools tools; ln -s ../../tools/packet-packer packet-packer
      - packer build -var 'plan=x1.small.x86' -var 'fac=sjc1' -var 'os=centos_7' -var 'mode=install' ../7/templates/centos-7.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  packer_centos7_c1xlarge:
    group: ci1
    image: image-ubuntu-test-env
    commands:
      - mkdir -p build/packer_centos7_c1xlarge
      - cd build/packer_centos7_c1xlarge
      - ln -s ../../scripts scripts; ln -s ../../tools tools; ln -s ../../tools/packet-packer packet-packer
      - packer build -var 'plan=c1.xlarge.x86' -var 'fac=sjc1' -var 'os=centos_7' -var 'mode=install' ../7/templates/centos-7.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  packer_centos7_c2medium:
    group: ci1
    image: image-ubuntu-test-env
    commands:
      - mkdir -p build/packer_centos7_c2medium
      - cd build/packer_centos7_c2medium
      - ln -s ../../scripts scripts; ln -s ../../tools tools; ln -s ../../tools/packet-packer packet-packer
      - packer build -var 'plan=c2.medium.x86' -var 'fac=sjc1' -var 'os=centos_7' -var 'mode=install' ../7/templates/centos-7.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  packer_centos7_m1xlarge:
    group: ci1
    image: image-ubuntu-test-env
    commands:
      - mkdir -p build/packer_centos7_m1xlarge
      - cd build/packer_centos7_m1xlarge
      - ln -s ../../scripts scripts; ln -s ../../tools tools; ln -s ../../tools/packet-packer packet-packer
      - packer build -var 'plan=m1.xlarge.x86' -var 'fac=sjc1' -var 'os=centos_7' -var 'mode=install' ../7/templates/centos-7.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  packer_centos7_m2xlarge:
    group: ci1
    image: image-ubuntu-test-env
    commands:
      - mkdir -p build/packer_centos7_m2xlarge
      - cd build/packer_centos7_m2xlarge
      - ln -s ../../scripts scripts; ln -s ../../tools tools; ln -s ../../tools/packet-packer packet-packer
      - packer build -var 'plan=m2.xlarge.x86' -var 'fac=sjc1' -var 'os=centos_7' -var 'mode=install' ../7/templates/centos-7.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  packer_centos7_s1large:
    group: ci1
    image: image-ubuntu-test-env
    commands:
      - mkdir -p build/packer_centos7_s1large
      - cd build/packer_centos7_s1large
      - ln -s ../../scripts scripts; ln -s ../../tools tools; ln -s ../../tools/packet-packer packet-packer
      - packer build -var 'plan=s1.large.x86' -var 'fac=sjc1' -var 'os=centos_7' -var 'mode=install' ../7/templates/centos-7.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

